# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7e4bf39a33eec3bd9a73035a2b6167e1321e9a4a5d7dcc747df28eb8f69448bd9a8bf3c3d6d3250e0add2ed9a8321d98da9fbaee8d7e041569600aab0b6d084

test:
  secret_key_base: 4e8e04fb17666da00aa01428b5462375d34c6ed7a88e25fa3582bcabf2c7b51c365a87c93ce8bc474bb1d3723f1240713f92a0beaa29109ab7ac3f9afdb2fdcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
